// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whutjfwifxczlceddsjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodXRqZndpZnhjemxjZWRkc2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjU2MzMsImV4cCI6MjA3MTI0MTYzM30.xNg5aNurOL__snDW0eonj9q6TzCOXe5E7z6QOpVwecc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});